### ISSUE TITLE
Example 5 import version mismatch?

### ISSUE THREAD

**Issue by andresrivero** [Edresson/VoiceSplit#8]
I was trying to load example # 5 in the readme locally, everything goes fine until the section after importing 
`import sys 
sys.path.insert(0, "./VoiceSplit/")
sys.path.insert(0, "./GE2E-Speaker-Encoder/")`

Maybe GE2E was updated after this was originally used, I couldn't find where in the version it fit. Just loading from the master branch causes an error like this: 

`        Testing the encoder...
Traceback (most recent call last):
  File "C:\Users\Studio\dev\voice\v.py", line 42, in <module>
    embed = encoder.embed_utterance(wav)
  File "C:\Users\Studio\dev\voice\./GE2E-Speaker-Encoder\encoder\inference.py", line 145, in embed_utterance
    frames = audio.wav_to_mel_spectrogram(wav)
  File "C:\Users\Studio\dev\voice\./GE2E-Speaker-Encoder\encoder\audio.py", line 48, in wav_to_mel_spectrogram
    frames = librosa.feature.melspectrogram(
TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given`

I'm not familiar with the GE2E branch to revert or modify it to be able to run. Any help would be appreciated :)

**Comment by justinjohn0306** [comment]
> I was trying to load example # 5 in the readme locally, everything goes fine until the section after importing `import sys sys.path.insert(0, "./VoiceSplit/") sys.path.insert(0, "./GE2E-Speaker-Encoder/")`
> 
> Maybe GE2E was updated after this was originally used, I couldn't find where in the version it fit. Just loading from the master branch causes an error like this:
> 
> ` Testing the encoder... Traceback (most recent call last): File "C:\Users\Studio\dev\voice\v.py", line 42, in <module> embed = encoder.embed_utterance(wav) File "C:\Users\Studio\dev\voice\./GE2E-Speaker-Encoder\encoder\inference.py", line 145, in embed_utterance frames = audio.wav_to_mel_spectrogram(wav) File "C:\Users\Studio\dev\voice\./GE2E-Speaker-Encoder\encoder\audio.py", line 48, in wav_to_mel_spectrogram frames = librosa.feature.melspectrogram( TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given`
> 
> I'm not familiar with the GE2E branch to revert or modify it to be able to run. Any help would be appreciated :)

Downgrade librosa to 0.9.1 or 0.9.2

``pip install librosa==0.9.1``
